FROM rust:1.75 as builder

WORKDIR /usr/src/conn-tracer
COPY . .

RUN rustup install stable
RUN rustup install nightly
RUN cargo install bpf-linker

RUN cargo xtask build-ebpf
RUN cargo build

FROM alpine:3.14

WORKDIR /usr/src/conn-tracer
COPY --from=builder /usr/src/conn-tracer/debug/conn-tracer /usr/src/conn-tracer/debug/conn-tracer
COPY --from=builder /usr/src/conn-tracer/bpfel-unknown-none/debug/conn-tracer /usr/src/conn-tracer/bpfel-unknown-none/debug/conn-tracer

ENTRYPOINT ["/usr/src/conn-tracer/debug/conn-tracer"]